spring:
  logging:
    level:
      root: DEBUG
      org.springframework.web: ERROR
      org.example.buckpal: INFO
      org.hibernate: ERROR
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

buckpal:
  transferThreshold: 10000


